<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="VARSHINI" failures="3" tests="19" name="tests.RoomServiceTests" time="4.701" errors="0" timestamp="2025-08-13T12:30:26 IST" skipped="0">
  <testcase classname="tests.RoomServiceTests" name="viewRoomList_status200" time="0.250"/>
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="viewRoomList_responseTimeBelow2s" time="0.236"/>
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="viewRoomList_bodyNotEmpty" time="0.238"/>
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="viewRoomList_bodyIsEmpty_Fail" time="0.248">
    <failure message="Intentional fail - body is expected null expected [null] but found [[{&quot;roomId&quot;:101,&quot;hotelId&quot;:&quot;H2001&quot;,&quot;roomType&quot;:&quot;SINGLE&quot;,&quot;roomStatus&quot;:&quot;AVAILABLE&quot;,&quot;roomPrice&quot;:1200.0},{&quot;roomId&quot;:301,&quot;hotelId&quot;:&quot;H2001&quot;,&quot;roomType&quot;:&quot;DELUXE&quot;,&quot;roomStatus&quot;:&quot;NOTAVAILABLE&quot;,&quot;roomPrice&quot;:5000.0},{&quot;roomId&quot;:701,&quot;hotelId&quot;:&quot;H2001&quot;,&quot;roomType&quot;:&quot;DOUBLE&quot;,&quot;roomStatus&quot;:&quot;AVAILABLE&quot;,&quot;roomPrice&quot;:5500.0}]]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Intentional fail - body is expected null expected [null] but found [[{"roomId":101,"hotelId":"H2001","roomType":"SINGLE","roomStatus":"AVAILABLE","roomPrice":1200.0},{"roomId":301,"hotelId":"H2001","roomType":"DELUXE","roomStatus":"NOTAVAILABLE","roomPrice":5000.0},{"roomId":701,"hotelId":"H2001","roomType":"DOUBLE","roomStatus":"AVAILABLE","roomPrice":5500.0}]]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotSame(Assert.java:1409)
at org.testng.Assert.assertNull(Assert.java:1342)
at tests.RoomServiceTests.viewRoomList_bodyIsEmpty_Fail(RoomServiceTests.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- viewRoomList_bodyIsEmpty_Fail -->
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="viewRoomById_status200" time="0.225"/>
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="viewRoomById_responseTimeBelow2s" time="0.228"/>
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="viewRoomById_contains101" time="0.237"/>
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="viewRoomByType_status200" time="0.280"/>
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="viewRoomByType_matchesType" time="0.239"/>
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="viewRoomByType_matchesType" time="0.222"/>
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="viewRoomByType_matchesType" time="0.267"/>
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="addRoom_statusCodeIs200" time="0.243"/>
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="addRoom_verifyRoomDetails" time="0.408">
    <failure message="expected [11] but found [10130170111]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [11] but found [10130170111]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at tests.RoomServiceTests.addRoom_verifyRoomDetails(RoomServiceTests.java:148)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- addRoom_verifyRoomDetails -->
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="addRoom_invalidRoomShouldNotExist_Fail" time="0.226">
    <failure message="Intentional fail - invalid roomId should not exist expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Intentional fail - invalid roomId should not exist expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at tests.RoomServiceTests.addRoom_invalidRoomShouldNotExist_Fail(RoomServiceTests.java:160)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- addRoom_invalidRoomShouldNotExist_Fail -->
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="updateRoomPrice_statusCodeIs200" time="0.228"/>
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="updateRoomPrice_verifyUpdatedPriceInResponse" time="0.203"/>
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="deleteRoomById_statusCodeIs200" time="0.233"/>
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="deleteRoomById_verifyRoomIsDeleted" time="0.248"/>
  <system-out/>
  <testcase classname="tests.RoomServiceTests" name="deleteRoomById_roomStillExists_Fail" time="0.242"/>
  <system-out/>
</testsuite> <!-- tests.RoomServiceTests -->
